services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${ODOO_DATABASE:-odoo}
      POSTGRES_USER: ${ODOO_DB_USER:-odoo}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: ${ODOO_DB_USER:-odoo}
      PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - ./odoo_addons:/mnt/extra-addons
    command:
      - odoo
      - --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

volumes:
  odoo-db-data:
